import os
from pathlib import Path
from supabase import create_client
from dotenv import load_dotenv

# load environment variables from .env
# We use the script's location to find the .env file in the parent directory (backend/)
script_dir = Path(__file__).resolve().parent
backend_dir = script_dir.parent
env_path = backend_dir / ".env"
load_dotenv(env_path)

# read Supabase credentials from environment
SUPABASE_URL = os.getenv("SUPABASE_URL")
# The .env file uses SUPABASE_SERVICE_ROLE_KEY, so we must use that key
SUPABASE_SECRET_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

if not SUPABASE_URL or not SUPABASE_SECRET_KEY:
    print(f"Debug: SUPABASE_URL={SUPABASE_URL}")
    print(f"Debug: SUPABASE_SECRET_KEY={'[SET]' if SUPABASE_SECRET_KEY else 'None'}")
    raise RuntimeError("Missing Supabase environment variables")

# create Supabase client (authenticated as backend role)
supabase = create_client(SUPABASE_URL, SUPABASE_SECRET_KEY)

# dummy data to insert into the database
dummy_users = [
    {"name": "Alice Johnson", "email": "alice@example.com"},
    {"name": "Bob Smith", "email": "bob@example.com"},
    {"name": "Charlie Lee", "email": "charlie@example.com"},
]

# insert data into the 'users' table using upsert
try:
    # Using upsert allows us to update existing records if they match on the unique key (email)
    response = supabase.table("users").upsert(dummy_users, on_conflict="email").execute()
    
    # print inserted rows
    print("Seeding successful!")
    print(response.data)

except Exception as e:
    error_msg = str(e)
    # Check for "relation "public.users" does not exist" or PGRST205 code
    if "PGRST205" in error_msg or "Could not find the table" in error_msg:
        print("\n" + "="*60)
        print("ERROR: The 'users' table does not exist in your Supabase database.")
        print("="*60)
        print("\nThe Supabase Python client connects via the REST API and cannot EXECUTE 'CREATE TABLE' statements.")
        print("You must create the table manually using the Supabase SQL Editor.\n")
        print("Run the following SQL query in your Supabase Dashboard:")
        print("-" * 40)
        print("""
CREATE TABLE public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
""")
        print("-" * 40)
        print("\nOnce created, run this script again to seed the data.")
    else:
        # Re-raise other errors
        print(f"An unexpected error occurred: {e}")
        raise e
